//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by fvmshell.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FVMSHETYPE                  129
#define IDS_ERRORMSG_FILENAMEINVALID    129
#define IDR_DIRVIEW                     130
#define IDS_HEADER_FILENAME             130
#define IDS_HEADER_FILESIZE             131
#define IDI_DOWN                        131
#define IDS_HEADER_FILETYPE             132
#define IDI_EMPTY                       132
#define IDS_HEADER_LASTMODIFIED         133
#define IDI_UP                          133
#define IDS_SIZE_BYTES                  134
#define IDD_ENTERSOMETHING              134
#define IDS_SIZE_GB                     135
#define IDD_SAPREFS                     135
#define IDS_SIZE_KBS                    136
#define IDR_FILEVIEW                    136
#define IDS_SIZE_MBS                    137
#define IDS_INPUTDIALOGTITLE_CREATEDIR  138
#define IDS_INPUTDIALOGTEXT_CREATEDIR   139
#define IDS_ERRORMSG_ENTERSTRING        140
#define IDS_ERRORMSG_VIEWEDIT_NODEFPROG 141
#define IDD_MAINFRAMEBAR                142
#define IDB_HOTTOOLBAR                  143
#define IDB_COLDTOOLBAR                 144
#define IDR_VIEW_DROP_DOWN              145
#define IDD_SETTING                     146
#define IDD_SETTING_VIEW                147
#define IDR_SHORTCUT                    148
#define IDD_SHORTCUT                    149
#define IDC_EDIT1                       1000
#define IDC_TEXT                        1001
#define IDC_GO                          1004
#define IDC_EDIT2                       1005
#define IDC_TAB1                        1006
#define IDC_VIEW_LARGE_ICONS            1010
#define IDC_VIEW_SMALL_ICONS            1011
#define IDC_VIEW_LIST                   1012
#define IDC_VIEW_DETAILS                1013
#define IDC_VIEW1_DETAILS               1013
#define IDC_SHORTCUT_BROWS              1015
#define IDC_SHORTCUT_EDIT               1016
#define ID_DIRVIEW_DELETE               32771
#define ID_DIRVIEW_RENAME               32772
#define ID_FILEVIEW_RENAME              32773
#define ID_TEMP                         32777
#define ID_MENU_LARGE_ICONS             32778
#define ID_MENU_SMALL_ICONS             32779
#define ID_MENU_LIST                    32780
#define ID_MENU_DETAILS                 32781
#define ID_FOLDER_OPTIONS               32782
#define ID_FILEVIEW_DELETE              32783
#define ID_FILEVIEW_NEWFOLDER           32784
#define ID_FILEVIEW_PROPERTIES          32785
#define ID_SHORTCUT_CREATESHORTCUT      32786
#define ID_SHORTCUT_DELETESHORTCUT      32787
#define IDS_HOME                        61446
#define IDS_FOLDER                      61446
#define ID_GO_BACK                      61447
#define IDS_BACK                        61448
#define ID_GO_FORWARD                   61449
#define IDS_FORWARD                     61450
#define ID_VIEW_STOP                    61451
#define ID_VIEW_UP                      61451
#define IDS_STOP                        61452
#define IDS_UP                          61452
#define ID_VIEW_REFRESH                 61453
#define IDS_REFRESH                     61454
#define ID_GO_START_PAGE                61455
#define ID_VIEW_FOLDER                  61455
#define ID_GO_SEARCH_THE_WEB            61456
#define IDS_SEARCH                      61457
#define ID_FAVORITES_DROPDOWN           61458
#define IDS_FAVORITES                   61459
#define IDS_PRINT                       61460
#define ID_FONT_DROPDOWN                61461
#define IDS_FONT                        61462
#define IDS_ADDRESS                     61463
#define IDS_ERRORMSG_PATHNOTFOUND       61464
#define IDS_VIEW_COPY                   61465
#define ID_VIEW_COPY                    61466
#define IDS_VIEW_PASTE                  61467
#define ID_VIEW_PASTE                   61468
#define IDS_VIEW_VIEW                   61469
#define IDS_DIRINFO_SELECTED_FILES      61470
#define IDS_DIRINFO_SELECTED_FILE       61471
#define IDS_DIRINFO_SELECTED_DIR        61472
#define IDS_DIRINFO_SELECTED_DIRS       61473
#define IDS_DIRINFO_SELECTED_DIRANDFILE 61474
#define IDS_DIRINFO_SELECTED_DIRANDFILES 61475
#define IDS_DIRINFO_SELECTED_DIRSANDFILE 61476
#define IDS_DIRINFO_SELECTED_DIRSANDFILES 61477
#define IDS_DIRINFO_EMPTY               61478
#define IDS_DIRINFO_FILE                61479
#define IDS_DIRINFO_FILES               61480
#define IDS_DIRINFO_DIR                 61481
#define IDS_DIRINFO_DIRS                61482
#define IDS_DIRINFO_DIRANDFILE          61483
#define IDS_DIRINFO_DIRANDFILES         61484
#define IDS_DIRINFO_DIRSANDFILE         61485
#define IDS_DIRINFO_DIRSANDFILES        61486
#define ID_VIEW_VIEW                    61487
#define IDS_VIEW_DELETE                 61488
#define ID_VIEW_DELETE                  61489
#define ID_SEPARATOR1                   61490
#define ID_SEPARATOR2                   61491
#define ID_SEPARATOR3                   61492
#define ID_VIEW_SHORTCUT                61493
#define IDS_VIEW_SHORTCUT               61494
#define ID_VIEW_RUN                     61495
#define IDS_VIEW_RUN                    61496

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
